---
title: "Introduction draft"
author: "Qimin Zhang"
date: "12/13/2019"
output: pdf_document
---

## Conclusion/Discussion

Based on the data set, gender demonstrates no association with salary from 1994 and 1995 after adjusting for department affliation, clinical emphasis, board certification status, rank, and experience. Therefore, we conclude that the data does not support the claim of gender discrimination in setting salaries at Houston College of Medicine. Moreover, department, clinical or research emphasis, board certified or not, and years of experience confound the association between salaries and gender. It's important to note that rank interacts with gender, meaning that salary among male and female physicians differ depending on the position held. 

The difference in salaries between male and female physicians at the Houston College of Medicine could be due to other factors, particularly rank since the claim on the failure in giving promotions to female faculty member was also in the lawsuit. Under the assumption that Houston College of Medicine, like most universities, operates under a tenature system, where salary is based on academic productivity, women in Houston College would get paid less based on the unproportional distribution of male full time professors compared to female full time professors, seen in [***insert table***] (Reed et al, 2011). Other studies have also shown that differences in salaries between male and female physicians may be due to characteristic differences that are affliated with gender roles such as specialty choice, number of hours worked, practice setting, and work-life balance (Baker, 1996 and Butkus et al, 2018). 

Futhermore, it was determined that physician 184 is an influential point based on the standardized residuals. Physician 184 is a male uncertified assistant professor in the department of medicine, with a research emphasis, a 5.1 publication rate, and has 2 years experience since obtaining MD. With all things considered, physician 184 has an unusually high salary. This could be due to other factors that were not included in this data set such as the importance of research and publication this particular physician was involved in or the number of hours he works.
