---
title: "Introduction draft"
author: "Jennifer Tang"
date: "12/10/2019"
output: pdf_document
---

## Introduction
Women being paid less than men is nothing new. In fact, this has been the norm ever since women started entering the workforce. In order to address such inequality, the Equal Pay Act and the Civil Rights Act were both signed into law in 1963 and 1964, respectively, with the purpose of prohibiting wage disparity based on sex and discrimination against employees based on sex, race, national origin, color and religion (Crampton et al, 1997). Despite the efforts to eliminate gender based wage gap, almost half a century later, a woman working full-time still only earns an average of 81.2 cents for every dollar a man working full-time earns in the U.S as of 2018 (United States Census Bureau, 2019). 

This issue is not only prevalent in the US, but also happens to transcends to other countries spanning within and between various occupations as well. One particular field of interest is in academic medicine. In the age of modern medicine, the diversity of medical practitioners has progressed substantially with more than one-third of physicians being women in a historically male dominated field, however compensation inequality still remains to be an issue that seeks improvement (Butkus, 2018). It was reported in a study conducted in 2016, that female physicians makes 90 cents for every dollar that a male physician makes in academic medicine (Freund et al, 2016). In addition to the wage disparity between male and female physicians, the lack of advancement in a female physician's career, despite the growing number of women entering the medical field, remains significant (Butkus, 2018). Many factors have been considered to contribute to such disparities such as speciality choice, hours worked, years of experience, and publication counts. 

These differences in wage and lack of promotions for female physicians can only be perceived as unfair and will eventually lead to a lawsuit. A few years ago, all the female physicians at Houston College of Medicine filed a lawsuit against the college for violating the Civil Rights Act of 1964 by engaging in consistent patterns and practice of discrimination against women faculty members in giving promotions and setting salaries. To address this situation, this paper explores the data set that the female faculty members presented of the different faculty positions held and salaries earned by the male and female physicians at Houston College of Medicine. Additional factors such as department affiliation, gender, board certification status, clinical or research emphasis, publication rate, and years of experience as a practicing physician, were also provided and examined. The goal is to find the associations that could support the claim of gender discrimination in the salary determination at this university hospital. 


## References

Baker, L. C. (1996). Differences in earnings between male and female physicians. New England Journal of Medicine, 334(15), 960-964.

Butkus, R., Serchen, J., Moyer, D. V., Bornstein, S. S., & Hingle, S. T. (2018). Achieving gender equity in physician compensation and career advancement: a position paper of the American College of Physicians. Annals of internal medicine, 168(10), 721-723.

Crampton, S. M., Hodge, J. W., & Mishra, J. M. (1997). The equal pay act: The first 30 years. Personnel Administration, 26(3), 335-344.

Freund, K. M., Raj, A., Kaplan, S. E., Terrin, N., Breeze, J. L., Urech, T. H., & Carr, P. L. (2016). Inequities in academic compensation by gender: A follow-up to the National Faculty Survey cohort study. Academic medicine: journal of the Association of American Medical Colleges, 91(8), 1068.

Reed, D. A., Enders, F., Lindor, R., McClees, M., & Lindor, K. D. (2011). Gender differences in academic productivity and leadership appointments of physicians throughout academic careers. Academic medicine, 86(1), 43-47.

United States Census Bureau. (2019). MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2018 INFLATION-ADJUSTED DOLLARS) OF WORKERS BY SEX AND WOMEN'S EARNINGS AS A PERCENTAGE OF MEN'S EARNINGS BY SELECTED CHARACTERISTICS. Retrieved from https://data.census.gov/cedsci/table?q=wage%20gap&g=&hidePreview=false&table=S2002&tid=ACSST1Y2018.S2002&lastDisplayedRow=19&vintage=2018

