---
title: "Qimin's model building"
author: "Qimin Zhang"
date: "12/7/2019"
output: 
  github_document:
  latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(dplyr)
```

```{r message=FALSE, warning=FALSE}
data = read_csv("data/Lawsuit.csv") %>% 
  janitor::clean_names() %>% 
  dplyr::select(-id) %>% 
  mutate(dept = as.factor(dept),
         gender = as.factor(gender),
         clin = as.factor(clin),
         cert = as.factor(cert),
         rank = as.factor(rank))
```

Look at the distribution of all variables.

```{r}
data %>%
  mutate(sal_average = (sal94 + sal95)/2) %>% 
  keep(is.numeric) %>%
  gather() %>% 
  ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_density() +
    labs(
    title = "Density plot of all numeric variables"
  )
```

We can see that they are all not normal. Let's try log transformation.

```{r}
data %>%
  mutate(sal_average = (sal94 + sal95)/2) %>%
  mutate(
    log_exper = log(exper),
    log_prate = log(prate),
    log_sal_average = log(sal_average),
    log_sal94 = log(sal94),
    log_sal95 = log(sal95)
  ) %>% 
  dplyr::select(-exper, -prate, -sal_average, -sal94, -sal95) %>% 
  keep(is.numeric) %>%
  gather() %>% 
  ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_density() +
    labs(
    title = "Density plot of all log numeric variables"
  )
```

The salaries and exper seem to be normal, while prate is still not normal.

```{r}
lm(log(sal_average) ~ . , data = data %>% mutate(sal_average = (sal94 + sal95)/2) %>% dplyr::select(-sal94, -sal95)) %>% 
  step(direction='backward') %>% 
  summary()
```


```{r}
lm(log(sal_average) ~ dept + clin + cert + exper + rank + gender + gender*dept + gender*clin + gender*cert + gender*exper + gender*rank, data = data %>% mutate(sal_average = (sal94 + sal95)/2) %>% dplyr::select(-sal94, -sal95)) %>% 
  summary()
```

```{r}
lm(log(sal_average) ~ dept + clin + cert + exper + rank + gender + gender*exper, data = data %>% mutate(sal_average = (sal94 + sal95)/2) %>% dplyr::select(-sal94, -sal95)) %>% 
  summary()
```

```{r}
lm(log(sal_average) ~ dept + clin + cert + exper + rank + gender + gender*exper, data = data %>% mutate(sal_average = (sal94 + sal95)/2) %>% dplyr::select(-sal94, -sal95)) %>% 
  summary()
```

