---
title: "References"
author: "Group 20 - James Ng, Jennifer tang, ZIqi, Qimin"
date: "12/14/2019"
output: word_document
---

## References

Baker, L. C. (1996). Differences in earnings between male and female physicians. New England Journal of Medicine, 334(15), 960-964.

Butkus, R., Serchen, J., Moyer, D. V., Bornstein, S. S., & Hingle, S. T. (2018). Achieving gender equity in physician compensation and career advancement: a position paper of the American College of Physicians. Annals of internal medicine, 168(10), 721-723.

Crampton, S. M., Hodge, J. W., & Mishra, J. M. (1997). The equal pay act: The first 30 years. Personnel Administration, 26(3), 335-344.

Freund, K. M., Raj, A., Kaplan, S. E., Terrin, N., Breeze, J. L., Urech, T. H., & Carr, P. L. (2016). Inequities in academic compensation by gender: A follow-up to the National Faculty Survey cohort study. Academic medicine: journal of the Association of American Medical Colleges, 91(8), 1068.

Reed, D. A., Enders, F., Lindor, R., McClees, M., & Lindor, K. D. (2011). Gender differences in academic productivity and leadership appointments of physicians throughout academic careers. Academic medicine, 86(1), 43-47.

United States Census Bureau. (2019). MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2018 INFLATION-ADJUSTED DOLLARS) OF WORKERS BY SEX AND WOMEN'S EARNINGS AS A PERCENTAGE OF MEN'S EARNINGS BY SELECTED CHARACTERISTICS. Retrieved from https://data.census.gov/cedsci/table?q=wage%20gap&g=&hidePreview=false&table=S2002&tid=ACSST1Y2018.S2002&lastDisplayedRow=19&vintage=2018


